In [11]:
import pandas as pd
import numpy as np

In [12]:
restaurants = pd.read_csv("list_of_restaurant.csv", index_col=0, sep=";", header=0)
restaurants

,City,Place_ID,Place_Name,Cuisine
154,Gdynia,ChIJK4PtjPun_UYRRYuECz2jxWk,10/10 Sushi,"['japanese', 'sushi']"
294,Sopot,ChIJvybH-5IK_UYRfeQa5nqUcfA,1911 Restaurant,"['turkish', 'chinese']"
269,Sopot,ChIJZTqg4JEK_UYReRYIAngM-9k,77 Sushi Sopot,['sushi']
256,Sopot,ChIJR_4eirUL_UYRCEVs1GUPXdY,A MODO MIO Da CIRO SOPOT,['italian']
109,Gdańsk,ChIJoypSPaFz_UYRe_809t6YJOQ,A la française,['french']
...,...,...,...,...
171,Gdynia,ChIJU0R9dJCn_UYR2RUow9ZYKr0,sushi.fresh,"['japanese', 'sushi']"
245,Sopot,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,Śliwka w Kompot,"['italian', 'turkish', 'pizza', 'chinese']"
231,Gdynia,ChIJxZgXuCuh_UYRXrGeVk7yKMc,Świeżo Sushi,"['japanese', 'sushi']"
11,Gdańsk,ChIJ3wv4m691_UYRMF7XZ3n62wg,„Bardzo Włosko!” Pizza i Wino,['italian']
7,Gdańsk,ChIJ2_nQun11_UYRSurD1dOvWoQ,兄弟面馆-Szybki Chińczyk Gdańsk,['chinese']

In [13]:
restaurants_details = pd.read_csv("list_of_restaurants_with_details.csv", index_col=0, sep=";", header=0)
restaurants_details

,Place_ID,Address,Phone Number,Price level,Avg rating,Amount of ratings,Vegetarian,Beer,Wine,Opening Hours,tags
0,ChIJK4PtjPun_UYRRYuECz2jxWk,"Świętojańska 48, 81-393 Gdynia, Poland",+48 534 454 824,NaN,4.4,229,NaN,True,NaN,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
1,ChIJvybH-5IK_UYRfeQa5nqUcfA,"Grunwaldzka 4/6, 81-759 Sopot, Poland",+48 572 945 145,NaN,4.7,524,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'bar', 'food', 'point_of_intere..."
2,ChIJZTqg4JEK_UYReRYIAngM-9k,"Bohaterów Monte Cassino 53, 81-767 Sopot, Poland",+48 662 208 719,2.0,4.4,466,True,True,True,NaN,"['restaurant', 'food', 'point_of_interest', 'e..."
3,ChIJR_4eirUL_UYRCEVs1GUPXdY,"Morska 16, 81-764 Sopot, Poland",+48 58 342 71 16,2.0,4.4,1324,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'point_of_interest', 'food', 'e..."
4,ChIJoypSPaFz_UYRe_809t6YJOQ,"Spichrzowa 24, 80-750 Gdańsk, Poland",+48 58 765 11 12,2.0,4.6,1419,True,True,True,"[{'close': {'day': 0, 'time': '1800'}, 'open':...","['grocery_or_supermarket', 'store', 'restauran..."
...,...,...,...,...,...,...,...,...,...,...,...
297,ChIJU0R9dJCn_UYR2RUow9ZYKr0,"Żołnierzy I Armii Wojska Polskiego 2, 81-380 G...",+48 781 296 414,2.0,4.8,612,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
298,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,"Bohaterów Monte Cassino 42, 81-759 Sopot, Poland",+48 733 000 533,2.0,4.7,12720,True,True,True,"[{'close': {'day': 1, 'time': '0200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
299,ChIJxZgXuCuh_UYRXrGeVk7yKMc,"Nowowiczlińska 24, 81-577 Gdynia, Poland",+48 570 700 285,NaN,4.9,892,True,NaN,NaN,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
300,ChIJ3wv4m691_UYRMF7XZ3n62wg,"Przytulna 9/U4, 80-176 Gdańsk, Poland",+48 730 099 290,2.0,4.8,1166,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
301,ChIJ2_nQun11_UYRSurD1dOvWoQ,"Poland, Gdańsk, Stanisława Wyspiańskiego, 1A邮政...",+48 510 003 630,NaN,4.3,95,NaN,NaN,NaN,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."

In [14]:
restaurants_total = pd.merge(restaurants, restaurants_details, on = ['Place_ID'])
restaurants_total.reset_index(drop=True, inplace=True)
restaurants_total

,City,Place_ID,Place_Name,Cuisine,Address,Phone Number,Price level,Avg rating,Amount of ratings,Vegetarian,Beer,Wine,Opening Hours,tags
0,Gdynia,ChIJK4PtjPun_UYRRYuECz2jxWk,10/10 Sushi,"['japanese', 'sushi']","Świętojańska 48, 81-393 Gdynia, Poland",+48 534 454 824,NaN,4.4,229,NaN,True,NaN,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
1,Sopot,ChIJvybH-5IK_UYRfeQa5nqUcfA,1911 Restaurant,"['turkish', 'chinese']","Grunwaldzka 4/6, 81-759 Sopot, Poland",+48 572 945 145,NaN,4.7,524,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'bar', 'food', 'point_of_intere..."
2,Sopot,ChIJZTqg4JEK_UYReRYIAngM-9k,77 Sushi Sopot,['sushi'],"Bohaterów Monte Cassino 53, 81-767 Sopot, Poland",+48 662 208 719,2.0,4.4,466,True,True,True,NaN,"['restaurant', 'food', 'point_of_interest', 'e..."
3,Sopot,ChIJR_4eirUL_UYRCEVs1GUPXdY,A MODO MIO Da CIRO SOPOT,['italian'],"Morska 16, 81-764 Sopot, Poland",+48 58 342 71 16,2.0,4.4,1324,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'point_of_interest', 'food', 'e..."
4,Gdańsk,ChIJoypSPaFz_UYRe_809t6YJOQ,A la française,['french'],"Spichrzowa 24, 80-750 Gdańsk, Poland",+48 58 765 11 12,2.0,4.6,1419,True,True,True,"[{'close': {'day': 0, 'time': '1800'}, 'open':...","['grocery_or_supermarket', 'store', 'restauran..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,Gdynia,ChIJU0R9dJCn_UYR2RUow9ZYKr0,sushi.fresh,"['japanese', 'sushi']","Żołnierzy I Armii Wojska Polskiego 2, 81-380 G...",+48 781 296 414,2.0,4.8,612,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
316,Sopot,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,Śliwka w Kompot,"['italian', 'turkish', 'pizza', 'chinese']","Bohaterów Monte Cassino 42, 81-759 Sopot, Poland",+48 733 000 533,2.0,4.7,12720,True,True,True,"[{'close': {'day': 1, 'time': '0200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
317,Gdynia,ChIJxZgXuCuh_UYRXrGeVk7yKMc,Świeżo Sushi,"['japanese', 'sushi']","Nowowiczlińska 24, 81-577 Gdynia, Poland",+48 570 700 285,NaN,4.9,892,True,NaN,NaN,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
318,Gdańsk,ChIJ3wv4m691_UYRMF7XZ3n62wg,„Bardzo Włosko!” Pizza i Wino,['italian'],"Przytulna 9/U4, 80-176 Gdańsk, Poland",+48 730 099 290,2.0,4.8,1166,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
319,Gdańsk,ChIJ2_nQun11_UYRSurD1dOvWoQ,兄弟面馆-Szybki Chińczyk Gdańsk,['chinese'],"Poland, Gdańsk, Stanisława Wyspiańskiego, 1A邮政...",+48 510 003 630,NaN,4.3,95,NaN,NaN,NaN,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."

In [15]:
restaurants_total['Vegetarian'] = restaurants_total['Vegetarian'].fillna(False)
restaurants_total['Beer'] = restaurants_total['Beer'].fillna(False)
restaurants_total['Wine'] = restaurants_total['Wine'].fillna(False)
restaurants_total

/tmp/ipykernel_41059/4264921294.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  restaurants_total['Vegetarian'] = restaurants_total['Vegetarian'].fillna(False)
/tmp/ipykernel_41059/4264921294.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  restaurants_total['Beer'] = restaurants_total['Beer'].fillna(False)
/tmp/ipykernel_41059/4264921294.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  restaurants_total['Wine'] = restaurants_total['Wine'].fillna(False)

,City,Place_ID,Place_Name,Cuisine,Address,Phone Number,Price level,Avg rating,Amount of ratings,Vegetarian,Beer,Wine,Opening Hours,tags
0,Gdynia,ChIJK4PtjPun_UYRRYuECz2jxWk,10/10 Sushi,"['japanese', 'sushi']","Świętojańska 48, 81-393 Gdynia, Poland",+48 534 454 824,NaN,4.4,229,False,True,False,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
1,Sopot,ChIJvybH-5IK_UYRfeQa5nqUcfA,1911 Restaurant,"['turkish', 'chinese']","Grunwaldzka 4/6, 81-759 Sopot, Poland",+48 572 945 145,NaN,4.7,524,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'bar', 'food', 'point_of_intere..."
2,Sopot,ChIJZTqg4JEK_UYReRYIAngM-9k,77 Sushi Sopot,['sushi'],"Bohaterów Monte Cassino 53, 81-767 Sopot, Poland",+48 662 208 719,2.0,4.4,466,True,True,True,NaN,"['restaurant', 'food', 'point_of_interest', 'e..."
3,Sopot,ChIJR_4eirUL_UYRCEVs1GUPXdY,A MODO MIO Da CIRO SOPOT,['italian'],"Morska 16, 81-764 Sopot, Poland",+48 58 342 71 16,2.0,4.4,1324,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'point_of_interest', 'food', 'e..."
4,Gdańsk,ChIJoypSPaFz_UYRe_809t6YJOQ,A la française,['french'],"Spichrzowa 24, 80-750 Gdańsk, Poland",+48 58 765 11 12,2.0,4.6,1419,True,True,True,"[{'close': {'day': 0, 'time': '1800'}, 'open':...","['grocery_or_supermarket', 'store', 'restauran..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,Gdynia,ChIJU0R9dJCn_UYR2RUow9ZYKr0,sushi.fresh,"['japanese', 'sushi']","Żołnierzy I Armii Wojska Polskiego 2, 81-380 G...",+48 781 296 414,2.0,4.8,612,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
316,Sopot,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,Śliwka w Kompot,"['italian', 'turkish', 'pizza', 'chinese']","Bohaterów Monte Cassino 42, 81-759 Sopot, Poland",+48 733 000 533,2.0,4.7,12720,True,True,True,"[{'close': {'day': 1, 'time': '0200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
317,Gdynia,ChIJxZgXuCuh_UYRXrGeVk7yKMc,Świeżo Sushi,"['japanese', 'sushi']","Nowowiczlińska 24, 81-577 Gdynia, Poland",+48 570 700 285,NaN,4.9,892,True,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
318,Gdańsk,ChIJ3wv4m691_UYRMF7XZ3n62wg,„Bardzo Włosko!” Pizza i Wino,['italian'],"Przytulna 9/U4, 80-176 Gdańsk, Poland",+48 730 099 290,2.0,4.8,1166,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
319,Gdańsk,ChIJ2_nQun11_UYRSurD1dOvWoQ,兄弟面馆-Szybki Chińczyk Gdańsk,['chinese'],"Poland, Gdańsk, Stanisława Wyspiańskiego, 1A邮政...",+48 510 003 630,NaN,4.3,95,False,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."

In [16]:
restaurants_total.groupby(["Price level"]).count()['Place_ID']

Price level
1.0     26
2.0    161
3.0     18
Name: Place_ID, dtype: int64

In [17]:
restaurants_total["Price level"].isna().sum()

115

In [18]:
restaurants_total['Price level'] = restaurants_total['Price level'].fillna(2.0)
restaurants_total

,City,Place_ID,Place_Name,Cuisine,Address,Phone Number,Price level,Avg rating,Amount of ratings,Vegetarian,Beer,Wine,Opening Hours,tags
0,Gdynia,ChIJK4PtjPun_UYRRYuECz2jxWk,10/10 Sushi,"['japanese', 'sushi']","Świętojańska 48, 81-393 Gdynia, Poland",+48 534 454 824,2.0,4.4,229,False,True,False,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
1,Sopot,ChIJvybH-5IK_UYRfeQa5nqUcfA,1911 Restaurant,"['turkish', 'chinese']","Grunwaldzka 4/6, 81-759 Sopot, Poland",+48 572 945 145,2.0,4.7,524,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'bar', 'food', 'point_of_intere..."
2,Sopot,ChIJZTqg4JEK_UYReRYIAngM-9k,77 Sushi Sopot,['sushi'],"Bohaterów Monte Cassino 53, 81-767 Sopot, Poland",+48 662 208 719,2.0,4.4,466,True,True,True,NaN,"['restaurant', 'food', 'point_of_interest', 'e..."
3,Sopot,ChIJR_4eirUL_UYRCEVs1GUPXdY,A MODO MIO Da CIRO SOPOT,['italian'],"Morska 16, 81-764 Sopot, Poland",+48 58 342 71 16,2.0,4.4,1324,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'point_of_interest', 'food', 'e..."
4,Gdańsk,ChIJoypSPaFz_UYRe_809t6YJOQ,A la française,['french'],"Spichrzowa 24, 80-750 Gdańsk, Poland",+48 58 765 11 12,2.0,4.6,1419,True,True,True,"[{'close': {'day': 0, 'time': '1800'}, 'open':...","['grocery_or_supermarket', 'store', 'restauran..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,Gdynia,ChIJU0R9dJCn_UYR2RUow9ZYKr0,sushi.fresh,"['japanese', 'sushi']","Żołnierzy I Armii Wojska Polskiego 2, 81-380 G...",+48 781 296 414,2.0,4.8,612,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
316,Sopot,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,Śliwka w Kompot,"['italian', 'turkish', 'pizza', 'chinese']","Bohaterów Monte Cassino 42, 81-759 Sopot, Poland",+48 733 000 533,2.0,4.7,12720,True,True,True,"[{'close': {'day': 1, 'time': '0200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
317,Gdynia,ChIJxZgXuCuh_UYRXrGeVk7yKMc,Świeżo Sushi,"['japanese', 'sushi']","Nowowiczlińska 24, 81-577 Gdynia, Poland",+48 570 700 285,2.0,4.9,892,True,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
318,Gdańsk,ChIJ3wv4m691_UYRMF7XZ3n62wg,„Bardzo Włosko!” Pizza i Wino,['italian'],"Przytulna 9/U4, 80-176 Gdańsk, Poland",+48 730 099 290,2.0,4.8,1166,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
319,Gdańsk,ChIJ2_nQun11_UYRSurD1dOvWoQ,兄弟面馆-Szybki Chińczyk Gdańsk,['chinese'],"Poland, Gdańsk, Stanisława Wyspiańskiego, 1A邮政...",+48 510 003 630,2.0,4.3,95,False,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."

In [19]:
restaurants_total.dropna(subset=["Opening Hours"], inplace=True)
restaurants_total.drop_duplicates(subset=['Place_ID'], inplace=True)
restaurants_total.reset_index(inplace=True, drop=True)
restaurants_total

,City,Place_ID,Place_Name,Cuisine,Address,Phone Number,Price level,Avg rating,Amount of ratings,Vegetarian,Beer,Wine,Opening Hours,tags
0,Gdynia,ChIJK4PtjPun_UYRRYuECz2jxWk,10/10 Sushi,"['japanese', 'sushi']","Świętojańska 48, 81-393 Gdynia, Poland",+48 534 454 824,2.0,4.4,229,False,True,False,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
1,Sopot,ChIJvybH-5IK_UYRfeQa5nqUcfA,1911 Restaurant,"['turkish', 'chinese']","Grunwaldzka 4/6, 81-759 Sopot, Poland",+48 572 945 145,2.0,4.7,524,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'bar', 'food', 'point_of_intere..."
2,Sopot,ChIJR_4eirUL_UYRCEVs1GUPXdY,A MODO MIO Da CIRO SOPOT,['italian'],"Morska 16, 81-764 Sopot, Poland",+48 58 342 71 16,2.0,4.4,1324,True,True,True,"[{'close': {'day': 0, 'time': '2100'}, 'open':...","['restaurant', 'point_of_interest', 'food', 'e..."
3,Gdańsk,ChIJoypSPaFz_UYRe_809t6YJOQ,A la française,['french'],"Spichrzowa 24, 80-750 Gdańsk, Poland",+48 58 765 11 12,2.0,4.6,1419,True,True,True,"[{'close': {'day': 0, 'time': '1800'}, 'open':...","['grocery_or_supermarket', 'store', 'restauran..."
4,Gdynia,ChIJOwSt0BCn_UYRaX4pwWzfdTE,ALGA street food,['japanese'],"Świętojańska 13, 81-368 Gdynia, Poland",+48 537 361 313,2.0,4.7,1092,True,True,True,"[{'close': {'day': 0, 'time': '2000'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,Gdynia,ChIJU0R9dJCn_UYR2RUow9ZYKr0,sushi.fresh,"['japanese', 'sushi']","Żołnierzy I Armii Wojska Polskiego 2, 81-380 G...",+48 781 296 414,2.0,4.8,612,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['meal_takeaway', 'restaurant', 'food', 'point..."
278,Sopot,ChIJ7ZaTw5EK_UYRO3MOsVS1e_0,Śliwka w Kompot,"['italian', 'turkish', 'pizza', 'chinese']","Bohaterów Monte Cassino 42, 81-759 Sopot, Poland",+48 733 000 533,2.0,4.7,12720,True,True,True,"[{'close': {'day': 1, 'time': '0200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
279,Gdynia,ChIJxZgXuCuh_UYRXrGeVk7yKMc,Świeżo Sushi,"['japanese', 'sushi']","Nowowiczlińska 24, 81-577 Gdynia, Poland",+48 570 700 285,2.0,4.9,892,True,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
280,Gdańsk,ChIJ3wv4m691_UYRMF7XZ3n62wg,„Bardzo Włosko!” Pizza i Wino,['italian'],"Przytulna 9/U4, 80-176 Gdańsk, Poland",+48 730 099 290,2.0,4.8,1166,True,True,True,"[{'close': {'day': 0, 'time': '2200'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."
281,Gdańsk,ChIJ2_nQun11_UYRSurD1dOvWoQ,兄弟面馆-Szybki Chińczyk Gdańsk,['chinese'],"Poland, Gdańsk, Stanisława Wyspiańskiego, 1A邮政...",+48 510 003 630,2.0,4.3,95,False,False,False,"[{'close': {'day': 0, 'time': '2130'}, 'open':...","['restaurant', 'food', 'point_of_interest', 'e..."

In [20]:
restaurants_total.to_csv("all_restaurants_info.csv", sep=";", header=True)